/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.tsfile.interop;

import org.apache.tsfile.file.metadata.IDeviceID;
import org.apache.tsfile.read.TsFileReader;
import org.apache.tsfile.read.TsFileSequenceReader;
import org.apache.tsfile.read.common.Path;
import org.apache.tsfile.read.common.RowRecord;
import org.apache.tsfile.read.expression.QueryExpression;
import org.apache.tsfile.read.query.dataset.QueryDataSet;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Validates TsFile files generated by C# implementation. This class reads C#-generated V4 files and
 * verifies they can be parsed correctly by Java.
 */
public class CSharpFileValidator {

  private static final Logger LOGGER = LoggerFactory.getLogger(CSharpFileValidator.class);

  public static void main(String[] args) {
    if (args.length < 1) {
      System.err.println(
          "Usage: CSharpFileValidator <tsfile-path> [expected-device] [expected-rows]");
      System.err.println("  tsfile-path: Path to the C#-generated TsFile");
      System.err.println("  expected-device: Expected device name (optional)");
      System.err.println("  expected-rows: Expected number of rows (optional)");
      System.exit(1);
    }

    String filePath = args[0];
    String expectedDevice = args.length > 1 ? args[1] : null;
    Integer expectedRows = args.length > 2 ? Integer.parseInt(args[2]) : null;

    try {
      ValidationResult result = validateFile(filePath, expectedDevice, expectedRows);
      if (result.isSuccess()) {
        System.out.println("SUCCESS: " + result.getMessage());
        System.exit(0);
      } else {
        System.err.println("FAILED: " + result.getMessage());
        System.exit(1);
      }
    } catch (Exception e) {
      System.err.println("ERROR: " + e.getMessage());
      e.printStackTrace();
      System.exit(2);
    }
  }

  /**
   * Validates a C#-generated TsFile.
   *
   * @param filePath Path to the TsFile
   * @param expectedDevice Expected device name (optional)
   * @param expectedRows Expected number of rows (optional)
   * @return ValidationResult with success status and message
   */
  public static ValidationResult validateFile(
      String filePath, String expectedDevice, Integer expectedRows) {
    File file = new File(filePath);
    if (!file.exists()) {
      return ValidationResult.failure("File not found: " + filePath);
    }

    LOGGER.info("Validating C# file: {}", filePath);

    try (TsFileSequenceReader sequenceReader = new TsFileSequenceReader(filePath)) {
      // Check file version
      byte version = sequenceReader.readVersionNumber();
      LOGGER.info("File version: {}", version);

      if (version != 3 && version != 4) {
        return ValidationResult.failure(
            "Unexpected file version: " + version + " (expected 3 or 4)");
      }

      // Get all devices - convert IDeviceID to String
      Map<IDeviceID, List<String>> rawDeviceMeasurements =
          sequenceReader.getDeviceMeasurementsMap();
      Map<String, List<String>> deviceMeasurements = new HashMap<>();
      for (Map.Entry<IDeviceID, List<String>> entry : rawDeviceMeasurements.entrySet()) {
        deviceMeasurements.put(entry.getKey().toString(), entry.getValue());
      }
      LOGGER.info("Found {} devices", deviceMeasurements.size());

      if (deviceMeasurements.isEmpty()) {
        return ValidationResult.failure("No devices found in file");
      }

      // Log device info
      for (Map.Entry<String, List<String>> entry : deviceMeasurements.entrySet()) {
        LOGGER.info(
            "  Device: {} with {} measurements: {}",
            entry.getKey(),
            entry.getValue().size(),
            entry.getValue());
      }

      // If expected device specified, verify it exists
      if (expectedDevice != null && !deviceMeasurements.containsKey(expectedDevice)) {
        return ValidationResult.failure(
            "Expected device not found: "
                + expectedDevice
                + ". Available devices: "
                + deviceMeasurements.keySet());
      }

      // Read data using TsFileReader
      try (TsFileReader reader = new TsFileReader(sequenceReader)) {
        int totalRows = 0;

        for (Map.Entry<String, List<String>> entry : deviceMeasurements.entrySet()) {
          String device = entry.getKey();
          List<String> measurements = entry.getValue();

          if (measurements.isEmpty()) {
            continue;
          }

          // Build paths for query
          List<Path> paths = new ArrayList<>();
          for (String measurement : measurements) {
            paths.add(new Path(device, measurement, true));
          }

          QueryExpression queryExpression = QueryExpression.create(paths, null);
          QueryDataSet dataSet = reader.query(queryExpression);

          int deviceRows = 0;
          while (dataSet.hasNext()) {
            RowRecord record = dataSet.next();
            deviceRows++;
            totalRows++;

            // Log first few rows for debugging
            if (deviceRows <= 3) {
              LOGGER.debug(
                  "  Row {}: timestamp={}, fields={}",
                  deviceRows,
                  record.getTimestamp(),
                  record.getFields());
            }
          }

          LOGGER.info("  Device {} has {} rows", device, deviceRows);
        }

        LOGGER.info("Total rows read: {}", totalRows);

        // Verify expected rows if specified
        if (expectedRows != null && totalRows != expectedRows) {
          return ValidationResult.failure(
              "Row count mismatch: expected " + expectedRows + " but found " + totalRows);
        }

        return ValidationResult.success(
            String.format(
                "Successfully validated file (version=%d, devices=%d, rows=%d)",
                version, deviceMeasurements.size(), totalRows));
      }

    } catch (Exception e) {
      LOGGER.error("Error validating file", e);
      return ValidationResult.failure("Error reading file: " + e.getMessage());
    }
  }

  /** Result of file validation. */
  public static class ValidationResult {
    private final boolean success;
    private final String message;

    private ValidationResult(boolean success, String message) {
      this.success = success;
      this.message = message;
    }

    public static ValidationResult success(String message) {
      return new ValidationResult(true, message);
    }

    public static ValidationResult failure(String message) {
      return new ValidationResult(false, message);
    }

    public boolean isSuccess() {
      return success;
    }

    public String getMessage() {
      return message;
    }
  }
}
